INSERT INTO `wp_wic_interface` (`upload_field_name`, `matched_entity`, `matched_field`) VALUES
('ID', 'constituent', 'ID'),
('first', 'constituent', 'first_name'),
('fn', 'constituent', 'first_name'),
('fname', 'constituent', 'first_name'),
('f-name', 'constituent', 'first_name'),
('first name', 'constituent', 'first_name'),
('first_name', 'constituent', 'first_name'),
('middle_name', 'constituent', 'middle_name'),
('middle', 'constituent', 'middle_name'),
('mn', 'constituent', 'middle_name'),
('mi', 'constituent', 'middle_name'),
('initial', 'constituent', 'middle_name'),
('last', 'constituent', 'last_name'),
('ln', 'constituent', 'last_name'),
('lname', 'constituent', 'last_name'),
('l-name', 'constituent', 'last_name'),
('last name', 'constituent', 'last_name'),
('last_name', 'constituent', 'last_name'),
('address', 'address', 'address_line'),
('street address', 'address', 'address_line'),
('street_address', 'address', 'address_line'),
('addr ', 'address', 'address_line'),
('addr-1', 'address', 'address_line'),
('address_line', 'address', 'address_line'),
('city', 'address', 'city'),
('town', 'address', 'city'),
('city/town', 'address', 'city'),
('municipality', 'address', 'city'),
('state', 'address', 'state'),
('zip', 'address', 'zip'),
('email_address', 'email', 'email_address'),
('phone_number', 'phone', 'phone_number'),
('phone', 'phone', 'phone_number'),
('ext', 'phone', 'extension'),
('extension', 'phone', 'extension'),
('date_of_birth', 'constituent', 'date_of_birth'),
('dob', 'constituent', 'date_of_birth'),
('birth_date', 'constituent', 'date_of_birth'),
('birthday', 'constituent', 'date_of_birth'),
('gender', 'constituent', 'gender'),
('is_deceased', 'constituent', 'is_deceased'),
('address_type', 'address', 'address_type'),
('email_type', 'email', 'email_type'),
('phone_type', 'phone', 'phone_type'),
('case_status', 'constituent', 'case_status'),
('case_review_date', 'constituent', 'case_review_date'),
('activity_type', 'activity', 'activity_type'),
('activity_date', 'activity', 'activity_date'),
('activity_note', 'activity', 'activity_note'),
('issue', 'activity', 'issue'),
('post_title', 'issue', 'post_title'),
('post_content', 'issue', 'post_content'),
('post_category', 'issue', 'post_category'),
('tags_input', 'issue', 'tags_input'),
('pro_con', 'activity', 'pro_con'),
('wic_live_issue', 'issue', 'wic_live_issue');